name: recipe_makan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.5.3
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.6.12
  image_picker: ^1.2.1
  firebase_storage: ^12.4.10
  file_picker: ^8.0.0
  video_player: ^2.8.2
  chewie: ^1.7.1
  supabase_flutter: ^2.3.4
  webview_flutter: ^4.7.0
  path: ^1.8.3
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0




flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/







